

export const LOADING_BROWSE_POSTES = "LOADING_BROWSE_POSTES";
export const BROWSE_POSTES_LOADED = "BROWSE_POSTES_LOADED";
export const BROWSE_POSTES_LOADING_ERROR = "BROWSE_POSTES_LOADING_ERROR";
export const BROWSE_POST_LIKED = "BROWSE_POST_LIKED";
export const BROWSE_LIKE_POST_STARTING = "BROWSE_LIKE_POST_STARTING";
export const MORE_POSTES_LOADED = "MORE_POSTES_LOADED";